@host = http://localhost:10003/api/rest
@masterKey = 337E3E3EX3606X4227X9C0CXB90A65CE9BA8

### Get a list of actors (example, may not work if path is incorrect)
GET {{host}}/configure/actor/client
ITB_API_KEY: {{masterKey}}

### Create a domain
# @name createDomain
PUT {{host}}/domain
ITB_API_KEY: {{masterKey}}
content-type: application/json

{
  "shortName": "3My new domain",
  "fullName": "3My new domain",
  "description": "My new domain",
  "reportMetadata": "My new domain"
}

###
@domainKey = {{createDomain.response.body.apiKey}}


### Try to GET domain using captured key
GET {{host}}/domain/{{domainKey}}
ITB_API_KEY: {{masterKey}}


### Get all domains (optional)
GET http://localhost:9001/api/domains
ITB_API_KEY: {{masterKey}}
content-type: application/json

### Create a community
# @name createCommunity
PUT {{host}}/community
ITB_API_KEY: {{masterKey}}
content-type: application/json

{
  "shortName": "My new community 3",
  "fullName": "My new community 3 - updated",
  "description": "My new Community for the conformance testing.",
  "supportEmail": "support@eupo.eu",
  "interactionNotifications": true,
  "domain": "{{domainKey}}"
}

###
@communityKey = {{createCommunity.response.body.apiKey}}

### Create an organisation
# @name createOrganisation

PUT {{host}}/organisation
ITB_API_KEY: {{communityKey}}
content-type: application/json

{
  "shortName": "My new organisation 3",
  "fullName": "My new organisation 3"
}

###
@organisationKey = {{createOrganisation.response.body.apiKey}}
###

### Create a system
# @name createSystem
PUT {{host}}/system
ITB_API_KEY: {{communityKey}}
content-type: application/json

{
  "shortName": "My new system 3",
  "fullName": "My new system 3",
  "description": "Description of my system",
  "organisation": "{{organisationKey}}"
}

###
@systemKey = {{createSystem.response.body.apiKey}}

### Create a specification
# @name createSpecification
PUT {{host}}/specification
ITB_API_KEY: {{communityKey}}
content-type: application/json

{
  "shortName": "My FHIR specification 3",
  "fullName": "My FHIR specification 3",
  "description": "Description of my specification",
  "reportMetadata": "My specification reportMetadata",
  "hidden": false,
  "displayOrder": 0,
  "domain": "{{domainKey}}"
}
###
@specificationKey = {{createSpecification.response.body.apiKey}}

### Create an actor
# @name createActor
PUT {{host}}/actor
ITB_API_KEY: {{communityKey}}
content-type: application/json

{
  "identifier": "order-receiver",
  "name": "Order Receiver 3",
  "description": "Actor responsible for receiving orders.",
  "reportMetadata": "Order Receiver Actor",
  "default": false,
  "hidden": false,
  "displayOrder": 0,
  "specification": "{{specificationKey}}"
}

###
@actorKey = {{createActor.response.body.apiKey}}

### Deploy test suite via JSON
PUT {{host}}/testsuite
ITB_API_KEY: {{communityKey}}
content-type: application/json

{
  "specification": "{{specificationKey}}",
  "ignoreWarnings": false,
  "replaceTestHistory": true,
  "updateSpecification": true
}

### Upload test suite ZIP (use terminal curl command)
# NOTE: REST Client does not support multipart uploads directly. Use curl in terminal.
# Update API key and specification if needed

# F8 : uploadTestSuite
# Run this from terminal:
# curl -F updateSpecification=true \
#      -F specification={{specificationKey}} \
#      -F testSuite=@test-suite.zip \
#      --header "ITB_API_KEY: {{communityKey}}" \
#      -X POST http://localhost:9001/api/rest/testsuite/deploy



### Create conformance statement
# @name createConformance

PUT {{host}}/conformance/{{systemKey}}/{{actorKey}}
ITB_API_KEY: {{organisationKey}}
content-type: application/json

###
@conformanceKey = {{createConformance.response.body.apiKey}}



### GET domains
GET http://localhost:10003/api/rest/domains
ITB_API_KEY: EC89D73EX157AX469EX8E47X00066BF6508B


### GET domain details
GET http://localhost:10003/api/rest/domain/96B86ED2XD112X4DE9XAE95X49B301C42EBC
ITB_API_KEY: EC89D73EX157AX469EX8E47X00066BF6508B



### GET spec in domain
GET http://localhost:10003/api/rest/domain/AFA6BA52X0375X446EXB595XAAD0516F96F1/specifications
ITB_API_KEY: EC89D73EX157AX469EX8E47X00066BF6508B