@host = http://localhost:8087/matchboxv3/fhir
### @host = https://test.ahdis.ch/matchbox/fhir

### Check if server is available
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Origin: http://localhost

### 
### verify that StructureDefinition is there on configured on matchbox
GET {{host}}/StructureDefinition?url=http://hsrt-kkrt.org/fhir/StructureDefinition/InfoWashSource HTTP/1.1


### Upload the StructureMap

### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./InfoWashSource-to-Bundle.map




### 
GET  {{host}}/StructureDefinition?url=http://hsrt-kkrt.org/fhir/StructureDefinition/InfoWashSource






### upload sd, InfoWashSource seems to contain the full definition
POST {{host}}/StructureDefinition HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

< ./InfoWashSourceSD.json

### upload sd 
POST {{host}}/StructureDefinition HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

< ./OBRSegment.json

### upload sd
POST {{host}}/StructureDefinition HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

< ./ORCSegment.json

### upload sd
POST {{host}}/StructureDefinition HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

< ./PIDSegment.json

### upload sd
POST {{host}}/StructureDefinition HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

< ./TQ1Segment.json

### upload sd
POST {{host}}/StructureDefinition HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

< ./DG1Segment.json


### Validate the source example, should return No fatal or error issues detected, the validation has passed"

POST {{host}}/$validate?profile=http://hsrt-kkrt.org/fhir/StructureDefinition/InfoWashSource  HTTP/1.1
Accept: application/json
Content-Type: application/fhir+json

< ./InfoWashSource.json


### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./StructureMap/pid-to-patient.map

### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./StructureMap/dg1-to-condition.map

### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./StructureMap/obr-to-servicerequest.map

### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./StructureMap/orc-to-servicerequest.map


### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./StructureMap/tq1-to-servicerequest.map

### Convert Textual representation of a FHIR Mapping Language to StructureMap resource
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+json
Content-Type: text/fhir-mapping

< ./StructureMap/ctx-to-provenance.map

### TODO wold need to to the other maps too, but just be fine for the first ones


### transform the provided source file 
POST {{host}}/StructureMap/$transform?source=http://hsrt-kkrt.org/fhir/StructureMap/InfoWashSource-to-Bundle HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./InfoWashSource.json